### ISSUE TITLE
Electron production build on mac quits unexpectedly

### ISSUE THREAD

**Issue by xariusdesai** [quasarframework/firebase-sample-apps#33]
Hi,

I ran a production build of the data/profile sample app to see if I could reproduce a bug I was having with my own project and on opening the finalised app, it immediately quits with an error. 

Here are the things I did to make sure I'm not making a mistake anywhere:

1. Downloaded the src as a zip and opened the profile folder in vscode (ironically I'm not that comfortable using git)
2. ran yarn
3. ran npm install
4. copied the firebase config variable in .quasar.env.json to the production object
5. added node script to package.json: "build":"QENV=production quasar build -m electron"
6. ran that
7. build completed successfully
8. opened Firebase Sample App User Profile

At this point it seems to crash immediately. I'm attaching a crash log, not really sure what I'm looking for here.
[crash log.txt](https://github.com/quasarframework/firebase-sample-apps/files/5875667/crash.log.txt)

Any ideas?

**Comment by adamkpurdy** [comment]
@xariusdesai Thanks for bringing this to my attention. I initially didn't develop these for Electron, but I'll have a look in the next 24 - 48hrs and submit a PR.

**Comment by adamkpurdy** [comment]
@xariusdesai UPDATE: Recently upgraded the deps on the sample apps. Also did a dev and production electron build. I wasn't able to recreate your error specifically, but I did have some production build errors of my own stemming from unhandled promise rejection errors. I fixed those and got a production build to work.

I going to wait to push the fix as I need to do some clean up and updates on the code as well as update the articles that correspond to these apps. I should have this done over the weekend and ready for Monday.

**Comment by xariusdesai** [comment]
@adamkpurdy No worries, I managed to solve the problem I was having - think it was the same unhandled promise rejection, but I wasn't sure as I had refactored a lot to async await rather than .then syntax (just personal preference) and wanted to check against the sample. Turned out I wasn't awaiting firebase login properly and trying to push my next route through too soon and getting stuck.

Cheers

**Comment by adamkpurdy** [comment]
The codebase has been updated to support Electron. 

_**Please note: the package.json files need to be updated to add scripts to inject Firebase configuration values into the app during build time. Also, linting errors will occur as there are a couple of console.log statements for development purposes. As Electron is not in the scope of these sample apps these linting issues will not be addressed.**_
