### ISSUE TITLE
Cannot get env variable

### ISSUE THREAD

**Issue by bangdragon** [quasarframework/firebase-sample-apps#52]
I try to setup env like the guide on website.
But when i try to alert(process.env.QENV.FIREBASE_CONFIG) or
alert(process.env.QENV) or alert(process.env)
is does not show anything.
So my app is not working

When alert(process.env.DEV) is shown true

**Comment by adamkpurdy** [comment]
@bangdragon Thanks for the question. I can't be exactly sure your problem, but it sounds like the environment flag isn't being set when you run your bash command to start your dev server. You might be running on a windows environment and need to use the modified script command:
`$ yarn dev:win`

Let me know if this helps.

**Comment by bangdragon** [comment]
I run on termux android. Thanks for answering

**Comment by adamkpurdy** [comment]
Hmm. Have you gotten Quasar to run in the mobile mode of your choice[Cordova, Capacitor] inside your android emulator  without Firebase yet? Then, my next question is can you get the Firebase sample app working in just a standard SPA mode on a chrome browser?

Your use case is a bit out of scope for the target audience of that article. I'd recommend you break down your use case in a few steps first as you're going to have to do some digging and research out of the support of this sample app directly focused on mobile app with Cordova or Capacitor.

If you'd like to speak to me directly about this on the discord server send a friend request to Adam (EN/US)#3185, and we can speak in DM. Thanks.
