### ISSUE TITLE
Router return blank page

### ISSUE THREAD

**Issue by bangdragon** [quasarframework/firebase-sample-apps#59]
I setup project using quasar2 vue3 firebase9. Then follow your authenyicstion tutorial with some edit to adapt to my project setup.
Yarn dev show blank page of this url:
http://localhost:8080/auth/login
No error return
How to fix this. Thanks

**Comment by adamkpurdy** [comment]
@bangdragon **As I said in your last issue please friend request me:Adam (EN/US)#3185 on the** [Quasar discord](https://discord.com/invite/5TDhbDg) and we can chat there. You're not using Github issues properly, nor are you providing any insight to your reproduction steps or what you actually edited for adoption to your project needs.

**Comment by bangdragon** [comment]
I tried to connect with you on Discord but the app said you did not allowed

**Comment by adamkpurdy** [comment]
Ah ok. Friend request sent from me!
