### ISSUE TITLE
Upgrade to Firebase 9, Quasar 2 and ES6?

### ISSUE THREAD

**Issue by eugenevk** [quasarframework/firebase-sample-apps#71]
Could you update the code to work with Quasar 2 (VueJS 3, Composition API), Firebase 9, and ES6?

**Comment by adamkpurdy** [comment]
@eugenevk Thanks for asking. I've thought about it a bit, but have not started anything. Have a look at these community folks that have done work in this area:

@ldiebold: Luke has a good handful of Firebase Quasar-related repos that focus on what you mentioned and much more. He's a great guy and has a [youtube](https://www.youtube.com/c/LukeDiebold/videos) channel going over this stuff. 

@tmoreland72: Troy is another great guy and industry veteran. Speaking with him recently, and I believe he's added a reference in the #jobs Quasar Discord channel to his latest [Firebase Auth](https://github.com/kpapro/q-firebase-sandbox) repo with the modern approaches.

Hope this helps.

**Comment by eugenevk** [comment]
Thanks @adamkpurdy! Much appreciated and I'll explore.

**Comment by ldiebold** [comment]
@eugenevk take a look at https://quasar.vueauth.com

This will also scaffold out the entire UI for you (login, register, logout, password reset, password update etc) and you can configure all these components to your hearts content!
