### ISSUE TITLE
Please Handle data loading errors

### ISSUE THREAD

**Issue by rashidpathiyil** [quasarframework/firebase-sample-apps#8]
Request you to add an error handling while fetching data from the firebase.
Now it keeps showing the loading screen when the device is offline.
also, it's showing an error message on console `net::ERR_INTERNET_DISCONNECTED`

Thank you

**Comment by adamkpurdy** [comment]
@rashidpathiyil It sounds like you're specifically referring to just a single error that is not being handled in the UI correctly when the app does not have an internet connection based on your message.

Thank you for pointing this out, and if that is your request this is an issue of configuring the web application for [offline persistance](https://firebase.google.com/docs/firestore/manage-data/enable-offline#configure_offline_persistence). Is this what you are referring to?

**Comment by rashidpathiyil** [comment]
If a user navigates to profile.vue without internet connection, loading screen keep showing.

**Comment by adamkpurdy** [comment]
[Updated](https://github.com/quasarframework/firebase-sample-apps/commit/2ad195eaaba7b0ed70f87c5965f78ce586363144) messaging for the overlay when network connectivity is lost.
